### ISSUE TITLE
Simplify project install 

### ISSUE THREAD

**Issue by leonardiwagner** [VivaReal/ng-viva-ui#1]
Hey, why won't make ready to go with only `npm install` instead `npm install && npm run installdep`?

- Natural way of install a npm project
- Less steps for build on local machine
- Less steps for build on CI and deployment server

**Comment by rafaeltavares** [comment]
This package is distributed as prebuilt, so the npm install script will run bower each time someone uses it as a dependency. That's why.
We still rely on globals to run our unit tests, but this will change in the future.

**Comment by leonardiwagner** [comment]
Alright, that's fine so :smile: , thank you
